In [1]:
%matplotlib inline
%load_ext autoreload
%autoreload 2

In [2]:
import os
import warnings
warnings.filterwarnings('ignore')
os.environ["PYTHONWARNINGS"] = "ignore"

In [3]:
cur_folder_name = os.getcwd().split('/')[-1]
if cur_folder_name != "Virny":
    os.chdir("../..")

print('Current location: ', os.getcwd())

Current location:  /Users/denys_herasymuk/UCU/4course_2term/Bachelor_Thesis/Code/Virny

# Multiple Models Interface With No Bootstrap

In this example, we are going to conduct a deep performance profiling for 4 models. The only difference with the multiple models interface tutorial is the use of the `no_bootstrap` computation mode. This mode is useful in the case we do not need to measure stability abd uncertainty metrics, but want to measure only accuracy and classic fairness metrics. The computation mode disables the bootstrap approach and greatly speed-up metric computation.

For that, we will use `compute_metrics_with_config` interface that can compute metrics for multiple models. Thus, we will need to do the next steps:

* Initialize input variables

* Compute subgroup metrics

* Perform disparity metrics composition using the Metric Composer

* Create static visualizations using the Metric Visualizer

## Import dependencies

In [4]:
import os
from pprint import pprint
from datetime import datetime, timezone

from xgboost import XGBClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler

from virny.utils.custom_initializers import create_config_obj, read_model_metric_dfs, create_models_config_from_tuned_params_df
from virny.user_interfaces.multiple_models_api import compute_metrics_with_config
from virny.preprocessing.basic_preprocessing import preprocess_dataset
from virny.custom_classes.metrics_composer import MetricsComposer
from virny.utils.model_tuning_utils import tune_ML_models
from virny.datasets import CompasWithoutSensitiveAttrsDataset

## Initialize Input Variables

Based on the library flow, we need to create 3 input objects for a user interface:

* A **config yaml** that is a file with configuration parameters for different user interfaces for metric computation.

* A **dataset class** that is a wrapper above the user’s raw dataset that includes its descriptive attributes like a target column, numerical columns, categorical columns, etc. This class must be inherited from the BaseDataset class, which was created for user convenience.

* Finally, a **models config** that is a Python dictionary, where keys are model names and values are initialized models for analysis. This dictionary helps conduct audits for different analysis modes and analyze different types of models.

In [5]:
DATASET_SPLIT_SEED = 42
MODELS_TUNING_SEED = 42
TEST_SET_FRACTION = 0.2

In [6]:
models_params_for_tuning = {
    'DecisionTreeClassifier': {
        'model': DecisionTreeClassifier(random_state=MODELS_TUNING_SEED),
        'params': {
            "max_depth": [20, 30],
            "min_samples_split" : [0.1],
            "max_features": ['sqrt'],
            "criterion": ["gini", "entropy"]
        }
    },
    'LogisticRegression': {
        'model': LogisticRegression(random_state=MODELS_TUNING_SEED),
        'params': {
            'penalty': ['l2'],
            'C' : [0.0001, 0.1, 1, 100],
            'solver': ['newton-cg', 'lbfgs'],
            'max_iter': [250],
        }
    },
    'RandomForestClassifier': {
        'model': RandomForestClassifier(random_state=MODELS_TUNING_SEED),
        'params': {
            "max_depth": [6, 10],
            "min_samples_leaf": [1],
            "n_estimators": [50, 100],
            "max_features": [0.6]
        }
    },
    'XGBClassifier': {
        'model': XGBClassifier(random_state=MODELS_TUNING_SEED, verbosity=0),
        'params': {
            'learning_rate': [0.1],
            'n_estimators': [200],
            'max_depth': [5, 7],
            'lambda':  [10, 100]
        }
    }
}

### Create a config object

`compute_metrics_with_config` interface requires that your **yaml file** includes the following parameters:

* **dataset_name**: str, a name of your dataset; it will be used to name files with metrics.

* **computation_mode**: str, 'default', 'error_analysis', or 'no_bootstrap'. Name of the computation mode.

* **random_state**: int, a seed to control the randomness of the whole model evaluation pipeline.

* **sensitive_attributes_dct**: dict, a dictionary where keys are sensitive attribute names (including intersectional attributes), and values are disadvantaged values for these attributes. Intersectional attributes must include '&' between sensitive attributes. You do not need to specify disadvantaged values for intersectional groups since they will be derived from disadvantaged values in sensitive_attributes_dct for each separate sensitive attribute in this intersectional pair.

Note that disadvantaged value in a sensitive attribute dictionary must be **the same as in the original dataset**. For example, when distinct values of the _sex_ column in the original dataset are 'F' and 'M', and after pre-processing they became 0 and 1 respectively, you still need to set a disadvantaged value as 'F' or 'M' in the sensitive attribute dictionary.

In [7]:
ROOT_DIR = os.path.join('docs', 'examples')
config_yaml_path = os.path.join(ROOT_DIR, 'experiment_config.yaml')
config_yaml_content = """
dataset_name: COMPAS_Without_Sensitive_Attributes
computation_mode: no_bootstrap
random_state: 42
sensitive_attributes_dct: {'sex': 1, 'race': 'African-American', 'sex&race': None}
"""

with open(config_yaml_path, 'w', encoding='utf-8') as f:
    f.write(config_yaml_content)

In [8]:
config = create_config_obj(config_yaml_path=config_yaml_path)
SAVE_RESULTS_DIR_PATH = os.path.join(ROOT_DIR, 'results', f'{config.dataset_name}_Metrics_{datetime.now(timezone.utc).strftime("%Y%m%d__%H%M%S")}')

### Preprocess the dataset and create a BaseFlowDataset class

Based on the BaseDataset class, your **dataset class** should include the following attributes:

* **Obligatory attributes**: dataset, target, features, numerical_columns, categorical_columns

* **Optional attributes**: X_data, y_data, columns_with_nulls

For more details, please refer to the library documentation.

In [9]:
data_loader = CompasWithoutSensitiveAttrsDataset()
data_loader.X_data[data_loader.X_data.columns[:5]].head()

,juv_fel_count,juv_misd_count,juv_other_count,priors_count,age_cat_25 - 45
0,0.0,-2.340451,1.0,-15.010999,1
1,0.0,0.000000,0.0,0.000000,1
2,0.0,0.000000,0.0,0.000000,0
3,0.0,0.000000,0.0,6.000000,1
4,0.0,0.000000,0.0,7.513697,1

In [10]:
column_transformer = ColumnTransformer(transformers=[
    ('categorical_features', OneHotEncoder(handle_unknown='ignore', sparse_output=False), data_loader.categorical_columns),
    ('numerical_features', StandardScaler(), data_loader.numerical_columns),
])

In [11]:
base_flow_dataset = preprocess_dataset(data_loader=data_loader, 
                                       column_transformer=column_transformer,
                                       sensitive_attributes_dct=config.sensitive_attributes_dct,
                                       test_set_fraction=TEST_SET_FRACTION,
                                       dataset_split_seed=DATASET_SPLIT_SEED)

### Tune models and create a models config for metrics computation

In [12]:
tuned_params_df, models_config = tune_ML_models(models_params_for_tuning, base_flow_dataset, config.dataset_name, n_folds=3)
tuned_params_df

2024/12/14, 15:03:04: Tuning DecisionTreeClassifier...
2024/12/14, 15:03:06: Tuning for DecisionTreeClassifier is finished [F1 score = 0.6554846983071245, Accuracy = 0.6575048862828714]

2024/12/14, 15:03:06: Tuning LogisticRegression...
2024/12/14, 15:03:06: Tuning for LogisticRegression is finished [F1 score = 0.6483823116804864, Accuracy = 0.6520611566087312]

2024/12/14, 15:03:06: Tuning RandomForestClassifier...
2024/12/14, 15:03:06: Tuning for RandomForestClassifier is finished [F1 score = 0.6582739175359259, Accuracy = 0.6601120816372682]

2024/12/14, 15:03:06: Tuning XGBClassifier...
2024/12/14, 15:03:07: Tuning for XGBClassifier is finished [F1 score = 0.6649018515640065, Accuracy = 0.6669791262841636]

,Dataset_Name,Model_Name,F1_Score,Accuracy_Score,Model_Best_Params
0,COMPAS_Without_Sensitive_Attributes,DecisionTreeClassifier,0.655485,0.657505,"{'criterion': 'gini', 'max_depth': 20, 'max_fe..."
1,COMPAS_Without_Sensitive_Attributes,LogisticRegression,0.648382,0.652061,"{'C': 1, 'max_iter': 250, 'penalty': 'l2', 'so..."
2,COMPAS_Without_Sensitive_Attributes,RandomForestClassifier,0.658274,0.660112,"{'max_depth': 10, 'max_features': 0.6, 'min_sa..."
3,COMPAS_Without_Sensitive_Attributes,XGBClassifier,0.664902,0.666979,"{'lambda': 100, 'learning_rate': 0.1, 'max_dep..."

In [13]:
now = datetime.now(timezone.utc)
date_time_str = now.strftime("%Y%m%d__%H%M%S")
tuned_df_path = os.path.join(ROOT_DIR, 'results', 'models_tuning', f'tuning_results_{config.dataset_name}_{date_time_str}.csv')
tuned_params_df.to_csv(tuned_df_path, sep=",", columns=tuned_params_df.columns, float_format="%.4f", index=False)

Create models_config from the saved tuned_params_df for higher reliability

In [14]:
models_config = create_models_config_from_tuned_params_df(models_params_for_tuning, tuned_df_path)
pprint(models_config)

{'DecisionTreeClassifier': DecisionTreeClassifier(max_depth=20, max_features='sqrt', min_samples_split=0.1,
                       random_state=42),
 'LogisticRegression': LogisticRegression(C=1, max_iter=250, random_state=42, solver='newton-cg'),
 'RandomForestClassifier': RandomForestClassifier(max_depth=10, max_features=0.6, random_state=42),
 'XGBClassifier': XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, lambda=100, learning_rate=0.1,
              max_bin=None, max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=5, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=200, n_jobs=None,
              num_parallel_tree=None, ...)}

## Subgroup Metric Computation

After that we need to input the _BaseFlowDataset_ object, models config, and config yaml to a metric computation interface and execute it. The interface uses subgroup analyzers to compute different sets of metrics for each privileged and disadvantaged group. As for now, our library supports **Subgroup Variance Analyzer** and **Subgroup Error Analyzer**, but it is easily extensible to any other analyzers. When the variance and error analyzers complete metric computation, their metrics are combined, returned in a matrix format, and stored in a file if defined.

In [15]:
metrics_dct = compute_metrics_with_config(base_flow_dataset, config, models_config, SAVE_RESULTS_DIR_PATH,
                                          notebook_logs_stdout=True,
                                          with_predict_proba=False)

Analyze multiple models:   0%|          | 0/4 [00:00<?, ?it/s]

Look at several columns in top rows of computed metrics

In [16]:
sample_model_metrics_df = metrics_dct[list(models_config.keys())[0]]
sample_model_metrics_df[sample_model_metrics_df.columns[:6]].head(20)

           Metric      overall    sex_priv     sex_dis   race_priv    race_dis
0             TPR     0.615711    0.493333    0.638889    0.517007    0.660494
1             TNR     0.723077    0.830882    0.690423    0.786517    0.669811
2             PPV     0.641593    0.616667    0.645408    0.571429    0.670846
3             FNR     0.384289    0.506667    0.361111    0.482993    0.339506
4             FPR     0.276923    0.169118    0.309577    0.213483    0.330189
5        Accuracy     0.675189    0.710900    0.666272    0.690821    0.665109
6              F1     0.628386    0.548148    0.642132    0.542857    0.665630
7  Selection-Rate     0.428030    0.284360    0.463905    0.321256    0.496885
8     Sample_Size  1056.000000  211.000000  845.000000  414.000000  642.000000

## Disparity Metric Composition

To compose disparity metrics, the Metric Composer should be applied. **Metric Composer** is responsible for the second stage of the model audit. Currently, it computes our custom error disparity, stability disparity, and uncertainty disparity metrics, but extending it for new disparity metrics is very simple. We noticed that more and more disparity metrics have appeared during the last decade, but most of them are based on the same group specific metrics. Hence, such a separation of group specific and disparity metrics computation allows us to experiment with different combinations of group specific metrics and avoid group metrics recomputation for a new set of disparity metrics.

In [17]:
models_metrics_dct = read_model_metric_dfs(SAVE_RESULTS_DIR_PATH, model_names=list(models_config.keys()))

In [18]:
metrics_composer = MetricsComposer(models_metrics_dct, config.sensitive_attributes_dct)

Compute composed metrics

In [19]:
models_composed_metrics_df = metrics_composer.compose_metrics()

In [20]:
models_composed_metrics_df

,Metric,sex,race,sex&race,Model_Name
0,Accuracy_Difference,-0.044628,-0.025712,-0.052464,DecisionTreeClassifier
1,Equalized_Odds_FNR,-0.145556,-0.143487,-0.139463,DecisionTreeClassifier
2,Equalized_Odds_FPR,0.140459,0.116706,0.172376,DecisionTreeClassifier
3,Statistical_Parity_Difference,0.179545,0.175629,0.212669,DecisionTreeClassifier
4,Disparate_Impact,1.631400,1.546694,1.661918,DecisionTreeClassifier
5,Equalized_Odds_TNR,-0.140459,-0.116706,-0.172376,DecisionTreeClassifier
6,Equalized_Odds_TPR,0.145556,0.143487,0.139463,DecisionTreeClassifier
7,Accuracy_Difference,-0.004364,0.000226,-0.016544,LogisticRegression
8,Equalized_Odds_FNR,-0.187374,-0.264613,-0.242125,LogisticRegression
9,Equalized_Odds_FPR,0.100583,0.156102,0.187169,LogisticRegression
10,Statistical_Parity_Difference,0.172439,0.249560,0.267602,LogisticRegression
11,Disparate_Impact,1.596469,1.906296,1.914016,LogisticRegression
12,Equalized_Odds_TNR,-0.100583,-0.156102,-0.187169,LogisticRegression
13,Equalized_Odds_TPR,0.187374,0.264613,0.242125,LogisticRegression
14,Accuracy_Difference,-0.032822,-0.018872,-0.024306,RandomForestClassifier
15,Equalized_Odds_FNR,-0.071010,-0.167486,-0.155195,RandomForestClassifier
16,Equalized_Odds_FPR,0.084321,0.132888,0.146995,RandomForestClassifier
17,Statistical_Parity_Difference,0.125034,0.205224,0.218215,RandomForestClassifier
18,Disparate_Impact,1.361401,1.638817,1.648481,RandomForestClassifier
19,Equalized_Odds_TNR,-0.084321,-0.132888,-0.146995,RandomForestClassifier
20,Equalized_Odds_TPR,0.071010,0.167486,0.155195,RandomForestClassifier
21,Accuracy_Difference,0.005093,0.008398,-0.005309,XGBClassifier
22,Equalized_Odds_FNR,-0.126869,-0.168115,-0.153447,XGBClassifier
23,Equalized_Odds_FPR,0.057137,0.086602,0.111180,XGBClassifier
24,Statistical_Parity_Difference,0.127401,0.176554,0.195473,XGBClassifier
25,Disparate_Impact,1.368242,1.518393,1.558798,XGBClassifier
26,Equalized_Odds_TNR,-0.057137,-0.086602,-0.111180,XGBClassifier
27,Equalized_Odds_TPR,0.126869,0.168115,0.153447,XGBClassifier